name: 'KXCBridge: Tag Release'
description: 'Tag version for SPM'
author: 'Kevin Galligan'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  commitMessage:
    description: 'Message for Package.swift commit'
    required: true
  tagMessage:
    description: 'Message for release tag'
    required: true
  tagVersion:
    description: 'The release version'
    required: true
  branchName:
    description: 'Branch name'
    required: true

runs:
  using: node20
  main: dist/index.js
