name: 'KMMBridge: Local SPM Publishing Support'
description: 'Commit and tag SPM version.'
author: 'Kevin Galligan'

branding:
  icon: 'git-branch'
  color: 'orange'

inputs:
  commitMessage:
    description: 'Message for the commit which updates the `Package.swift` file.'
    required: true
  tagMessage:
    description: 'Message for the release tag. Defaults to "Version ${tagVersion}".'
    required: false
  tagVersion:
    description: 'Version string to use in the tag. Should follow [semver rules](https://semver.org/).'
    required: true
  branchName:
    description: 'Branch to create and build with. Safe to ignore this.'
    required: false
  remote:
    description: 'Remote to push to. Default to "origin".'
    required: false

runs:
  using: node20
  main: dist/index.js
